### ISSUE TITLE
polynomial example error 

### ISSUE THREAD

**Issue by magg** [datathings/greycat-samples#1]
I can compile it, but when I try to run it... this error appears

I'm using these versions:

```
	compile group: 'com.datathings', name: 'greycat', version: '8.3'
	
	compile group: 'com.datathings', name: 'greycat-leveldb', version: '8.3'
	
	compile group: 'com.datathings', name: 'greycat-ml', version: '8.3'
	
```

**ERROR**
```
java.lang.ClassCastException: greycat.internal.heap.HeapDoubleArray cannot be cast to [D
	at greycat.ml.regression.PolynomialNode.toString(PolynomialNode.java:356) ~[greycat-ml-8.3.jar:na]
	at com.miggonza.services.TestService.lambda$6(TestService.java:393) ~[bin/:na]
	at greycat.internal.CoreGraph$6$1$1.on(CoreGraph.java:377) ~[greycat-8.3.jar:na]
	at greycat.internal.CoreGraph$6$1$1.on(CoreGraph.java:338) ~[greycat-8.3.jar:na]
	at greycat.internal.BlackHoleStorage.get(BlackHoleStorage.java:46) ~[greycat-8.3.jar:na]
	at greycat.internal.CoreGraph$6$1.on(CoreGraph.java:338) ~[greycat-8.3.jar:na]
	at greycat.internal.CoreGraph$6$1.on(CoreGraph.java:320) ~[greycat-8.3.jar:na]
	at greycat.internal.BlackHoleStorage.lock(BlackHoleStorage.java:80) ~[greycat-8.3.jar:na]
	at greycat.internal.CoreGraph$6.on(CoreGraph.java:320) ~[greycat-8.3.jar:na]
	at greycat.internal.CoreGraph$6.on(CoreGraph.java:316) ~[greycat-8.3.jar:na]
	at greycat.internal.BlackHoleStorage.connect(BlackHoleStorage.java:72) ~[greycat-8.3.jar:na]
	at greycat.internal.CoreGraph.connect(CoreGraph.java:316) ~[greycat-8.3.jar:na]```

**Comment by dukeboard** [comment]
Thanks for reporting this is a regression. I take of it.

**Comment by assaad** [comment]
Thanks for reporting, fixed on main branch and on version 8 branch.
